# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lockDown' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lockDown
  pod 'LGSideMenuController','2.1.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'PromisedFuture'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleMaps'
  pod 'BottomPopup'
  pod 'DeviceKit', '~> 1.3'
  pod 'ReachabilitySwift'
  
  target 'lockDownTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lockDownUITests' do
    # Pods for testing
  end

end
